Create portfolio entity
Cebix90/InvestmentTrackerApp pull request #7
Opened 2024-09-09 09:51 UTC by Cebix90

Created portfolio entity with tests

2024-09-11 21:52 UTC, Arturnix commented on src/main/java/com/cebix/investmenttrackerapp/databaseutils/CustomUserDAO.java
>                  fieldUpdater.accept(customUserToUpdate);
This code block can be one method.

2024-09-11 21:57 UTC, Arturnix commented on src/main/java/com/cebix/investmenttrackerapp/databaseutils/PortfolioDAO.java
> +                fieldUpdater.accept(portfolioToUpdate);
This code block can be one method with argument _portfolioToUpdate_ which is being returned.

2024-09-11 22:11 UTC, Arturnix requested changes
- Adding brief description of this application will help with using it.
- Despite I picked date in the future I didn't get error message: "You can only select a date at least one day in the past." (class FutureDateException, getMessage())
 but this one: "An unexpected error occurred. Please try again."
- Register and login links are visible in home page. Will they be used?
- 3 tests are failing:
MarketStatusAPIHandlerTests -> testGetMarketStatusData_ifCorrectResponse()
TechnicalIndicatorsAPIHandlerTests -> TestEMAData -> testGetEMAData_ifSuccess()
TechnicalIndicatorsAPIHandlerTests -> TestSMADData -> testGetSMADData_ifSuccess()

2024-09-11 22:11 UTC, Arturnix commented on src/main/java/com/cebix/investmenttrackerapp/databaseutils/CustomUserDAO.java
>                  fieldUpdater.accept(customUserToUpdate);
This code block can be one method which takes an argument customUserToUpdate and which is being returned.

2024-09-11 22:11 UTC, Arturnix commented on src/main/java/com/cebix/investmenttrackerapp/databaseutils/PortfolioDAO.java
> +                fieldUpdater.accept(portfolioToUpdate);
This code block can be one method with argument portfolioToUpdate which is being returned.

2024-09-11 22:11 UTC, Arturnix commented on src/test/java/com/cebix/investmenttrackerapp/databaseutils/PortfolioDAOTests.java
> +                CustomUser userForTests = createAndSaveUserForTests();
This code repeats, Maybe @BeforeClass or turning it into method will help.

2024-09-15 19:21 UTC, Cebix90 commented on src/main/java/com/cebix/investmenttrackerapp/databaseutils/CustomUserDAO.java
>                  fieldUpdater.accept(customUserToUpdate);
I specially created this method this way to update the methods for each important field separately to get better control over them

2024-09-15 19:21 UTC, Cebix90 commented on src/main/java/com/cebix/investmenttrackerapp/databaseutils/PortfolioDAO.java
> +                fieldUpdater.accept(portfolioToUpdate);
I specially created this method this way to update the methods for each important field separately to get better control over them

2024-09-15 20:26 UTC, Cebix90 commented on src/test/java/com/cebix/investmenttrackerapp/databaseutils/PortfolioDAOTests.java
> +                CustomUser userForTests = createAndSaveUserForTests();
Very good idea, I moved initialization of CustomUser object to @BeforeEach

2024-09-15 21:00 UTC, Cebix90 commented
> * Adding brief description of this application will help with using it.
> * Despite I picked date in the future I didn't get error message: "You can only select a date at least one day in the past." (class FutureDateException, getMessage())
>   but this one: "An unexpected error occurred. Please try again."
> * Register and login links are visible in home page but without routing in controller. Will they be used?
> * 3 tests are failing:
>   MarketStatusAPIHandlerTests -> testGetMarketStatusData_ifCorrectResponse()
>   TechnicalIndicatorsAPIHandlerTests -> TestEMAData -> testGetEMAData_ifSuccess()
>   TechnicalIndicatorsAPIHandlerTests -> TestSMADData -> testGetSMADData_ifSuccess()

I'll add small description soon, thanks for point me that.
I found a reason why bad error message occurs when current or future date was chosen, problem solved (commit pushed)
In future Register and Login links will work properly.
Tests to be refactored, thanks for info

2024-09-18 20:26 UTC, Arturnix commented on src/main/java/com/cebix/investmenttrackerapp/services/StockService.java
This method _public Stock retrieveStockData(String ticker, String date)_ has few hardcoded operations which are performed inside it. It maybe a good approach to put some block of codes to separate private methods.

For example here You can make checker method which takes _ticker_ as an parameter.

2024-09-18 20:26 UTC, Arturnix commented on src/main/java/com/cebix/investmenttrackerapp/services/StockService.java
>          LocalDate selectedDate;
This hardcoded method could be moved to separate private method to provide selectedDate as an output of this method.

2024-09-18 20:52 UTC, Cebix90 commented on src/main/java/com/cebix/investmenttrackerapp/services/StockService.java
Good idea, extracted some parts of code to smaller private methods

2024-09-20 10:48 UTC, blazejprzyluski commented on src/main/java/com/cebix/investmenttrackerapp/databaseutils/CustomUserDAO.java
> +        return email != null && !email.trim().isEmpty();
This does not check the email format

2024-09-20 10:48 UTC, blazejprzyluski commented on src/main/java/com/cebix/investmenttrackerapp/databaseutils/CustomUserDAO.java
> +        return password != null && !password.trim().isEmpty();
Password could use more validation

2024-09-20 10:48 UTC, blazejprzyluski commented on src/test/java/com/cebix/investmenttrackerapp/databaseutils/CustomUserDAOTests.java
> +    PortfolioDAO portfolioDAO;
private?

2024-09-20 10:48 UTC, blazejprzyluski commented on src/test/java/com/cebix/investmenttrackerapp/databaseutils/CustomUserDAOTests.java
> +        newUser.setPortfolio(null);
why null?

2024-09-20 10:48 UTC, blazejprzyluski commented on src/test/java/com/cebix/investmenttrackerapp/databaseutils/PortfolioDAOTests.java
> +    CustomUser userForTests;
private

2024-09-20 11:38 UTC, Cebix90 commented on src/test/java/com/cebix/investmenttrackerapp/databaseutils/CustomUserDAOTests.java
> +        newUser.setPortfolio(null);
user can be created without Portfolio, during CustomUserDao tests portfolio is not necessary

2024-09-20 11:59 UTC, Cebix90 commented on src/main/java/com/cebix/investmenttrackerapp/databaseutils/CustomUserDAO.java
> +        return email != null && !email.trim().isEmpty();
added the email format check

2024-09-20 15:22 UTC, Cebix90 commented on src/main/java/com/cebix/investmenttrackerapp/databaseutils/CustomUserDAO.java
> +        return password != null && !password.trim().isEmpty();
Good idea, I added restriction for password

2024-09-21 15:00 UTC, merged